### ISSUE TITLE
Web: Better validation of uploaded images

### ISSUE THREAD

**Issue by F30** [fausecteam/ctf-gameserver#19]
We had some security issues with uploaded team images at FAUST CTF 2018, where Cross Site Scripting was possible. There should be validation of the uploaded file extensions and maybe also file contents.

Besides that, we should add notes about setting `Content-Security-Policy` and maybe using a different domain for uploads in the documentation.

**Comment by maltek** [comment]
@F30 I took the liberty to push d0f028b for this. I still don't feel very comfortable about this code though. I'd prefer it if we removed the full-sized images completely (only keeping the thumbnail), and stored the image at a path that isn't user-controlled at all. Are you OK with that?

**Comment by F30** [comment]
@maltek: Thanks for the patch, however I'd suggest using Pull Requests for such stuff in the future.

The extension match should be case-insensitive in my opinion. We should also catch PIL/Pillow exception at opening (it will throw `OSError` for non-imge files) and turn decompression bombs into errors as described [in the Pillow docs](https://pillow.readthedocs.io/en/3.1.x/reference/Image.html#PIL.Image.open).

I'd like to keep full-size images around, but we may always convert them to PNG or so. How would you generate filenames? Adding a database field or using a salted hash come to my mind, however these options both seem a bit like overkill.

**Comment by F30** [comment]
> How would you generate filenames? Adding a database field or using a salted hash come to my mind, however these options both seem a bit like overkill.

I just realized that we could just use the team ID.

**Comment by F30** [comment]
Reopening this because we still need docs for `Content-Security-Policy`.
