### ISSUE TITLE
Controller, Submission, Checker: Run as different user than "nobody"

### ISSUE THREAD

**Issue by F30** [fausecteam/ctf-gameserver#29]
The unit files for the controller, submission and checker components launch their services as user "nobody".

It is of course reasonable to run them unprivileged, but running everything as "nobody" is problematic on its own. This especially subverts our privilege separation between the checker master and the checker scripts.

Other than creating separate accounts, a possible solution would be using systemd's `DynamicUser` feature.

**Comment by maltek** [comment]
> Other than creating separate accounts, a possible solution would be using systemd's DynamicUser feature.

If you go that way, remember to add something like `Environment=HOME=/tmp`, or else Python will throw some undecipherable exceptions during startup.

**Comment by F30** [comment]
Fixed for submission in b727719.
