### ISSUE TITLE
Web: Support providing per-team downloads

### ISSUE THREAD

**Issue by F30** [fausecteam/ctf-gameserver#42]
VPN configs could be distributed through a login-protected area of the website instead of/in addition to email.

That would required an option to provide downloads for individual teams. In order to be usable, such option would also have to support uploading the files for many teams at once.

**Comment by F30** [comment]
This would also enable FAUST CTF to keep registration open without a deadline and provide (pregenerated) configs to new teams in an ad-hoc fashion.

**Comment by TheJonny** [comment]
Würde vermutlichh deutlich support-aufwand sparen

**Comment by F30** [comment]
Architecture decision:

* We will store the files in a well-known hierarchy in the file system
* Organized by net number for now, organization by ID could be added in the future
* List of files, their names within the hierarchy, and description will be configured in the database
