### ISSUE TITLE
Controller, DB: Rethink bonus points

### ISSUE THREAD

**Issue by F30** [fausecteam/ctf-gameserver#49]
There is a "bonus" field in the "scoring_flag" table, which somehow gets incorporated into scoring but (hopefully) is never actually used. I don't know what the semantics of that are supposed to be, so we should remove it.

On the other hand, one might actually want to award bonus points to a team. However, these should not be tied to a particular flag.

It will probably be easier to implement this after #28.

**Comment by siccegge** [comment]
https://github.com/fausecteam/ctf-gameserver/blob/master/scripts/controller/ctf-scoring#L14

**Comment by F30** [comment]
@siccegge: Fair enough. Then, at the very least, this should be better documented and/or renamed.
