### ISSUE TITLE
Show Points per Service in CTF Time Scoreboard Feed

### ISSUE THREAD

**Issue by FlorianKothmeier** [fausecteam/ctf-gameserver#75]
The CTFTime scoreboard feed currently reports points split up as offense, defense and sla points instead of per service.
For reference, this is the scoreboard feed from FAUST CTF 2022: https://2022.faustctf.net/competition/scoreboard-ctftime.json

A side effec of this is, that CTFtime generates the list of tasks for writeups from this feed, resulting in the tasks "Offense" "Defense" and "SLA" after the CTF.

It would make more sense to report the points scored in each service instead, so that the correct services are created on CTFtime automatically and do not need to be fixed manually

**Comment by F30** [comment]
NB: CTFTime actually suggests to do it as we currently do in Example 3 on https://ctftime.org/json-scoreboard-feed. We will still change it.
